[2022-06-10T13:27:46.467045+00:00] main.ERROR: Exception: Me exception in C:\Apache24\htdocs\php\modules\main\Controller.php:25 Stack trace: #0 [internal function]: Modules\Main\Controller->exception() #1 C:\Apache24\htdocs\php\framework\Program.php(81): call_user_func_array(Array, Array) #2 C:\Apache24\htdocs\php\framework\Program.php(40): Framework\Program->route() #3 C:\Apache24\htdocs\php\public\index.php(10): Framework\Program->run() #4 {main} [] []
